query getArticles(
    $loc: [Locales]
    $limit: Int! = 15
    $site: String
    $status: String! = "Published"
    $rootUrl: String
    $articleTopic: [String]
) {
    ArticlePage(
        locale: $loc
        orderBy: { _metadata: { published: DESC } }
        limit: $limit
        where: {
            _metadata: {
                status: { eq: $status }
                url: { base: { eq: $site }, default: { startsWith: $rootUrl } }
            }
            ArticleTopic: { in: $articleTopic }
        }
    ) {
        items {
            ...ArticlePageExcerpt
        }
    }
}
