query getArticles(
    $loc: [Locales]
    $limit: Int! = 15
    $site: String
    $status: String! = "Published"
    $rootUrl: String
    $articleTopic: String
    $subtopicAuto: [String]
    $subtopicFinancialHardship: [String]
    $subtopicHome: [String]
    $subtopicLifeStages: [String]
    $subtopicPersonalFinances: [String]
    $subtopicRetirement: [String]
) {
    ArticlePage(
        locale: $loc
        orderBy: { _metadata: { published: DESC } }
        limit: $limit
        where: {
            _metadata: {
                status: { eq: $status }
                url: { base: { eq: $site }, default: { startsWith: $rootUrl } }
            }
            ArticleTaxonomy: {
                ArticleTopic: { eq: $articleTopic }
                SubtopicAuto: { in: $subtopicAuto }
                SubtopicFinancialHardship: { in: $subtopicFinancialHardship }
                SubtopicHome: { in: $subtopicHome }
                SubtopicLifeStages: { in: $subtopicLifeStages }
                SubtopicPersonalFinances: { in: $subtopicPersonalFinances }
                SubtopicRetirement: { in: $subtopicRetirement }
            }
        }
    ) {
        items {
            ...ArticlePageExcerpt
        }
    }
}
