fragment AbaWebinarPage on AbaWebinarPage {
    _metadata {
        ...PageUrl
        published
        displayName
    }
    WebinarTitle
    StartDateTime
    EndDateTime
    Restrictions
    Description {
        html
    }
    WebinarUrl
    Speakers
    SupportingAssets {
        ...ContentUrl
        ...ContentReferenceItem
    }
    ProductId
    NonMemberPrice
    MemberPrice
    CeCreditsAvailable
    CreditsDescription {
        html
    }
    Audience
    Schema
    SeoSettings {
        ...PageSeoSettingsProperty
    }
    PageAdminSettings {
        ...PageAdminSettingsProperty
    }
}
