fragment ArticlePage on ArticlePage {
    _metadata {
        ...PageUrl
        published
        displayName
        key
    }
    InsightType
    PromoImage {
        ...ContentUrl
    }
    Heading
    SubHeading
    Author
    Body {
        html
    }
    ReadTime
    CalculatorUrl
    CalculatorUsage {
        html
    }
    InfographicImage {
        ...ContentUrl
    }
    VideoYoutube
    VideoTranscriptLink {
        default
    }
    ArticleTaxonomy {
        ArticleTopic
        SubtopicAuto
        SubtopicFinancialHardship
        SubtopicHome
        SubtopicLifeStages
        SubtopicPersonalFinances
        SubtopicRetirement
    }
    Related {
        HideRelated
        CuratedInsights {
            ...ContentArea
        }
    }
    SeoSettings {
        ...PageSeoSettingsProperty
    }
    PageAdminSettings {
        ...PageAdminSettingsProperty
    }
}
