fragment ArticlePage on ArticlePage {
    _metadata {
        ...PageUrl
        published
        displayName
    }
    InsightType
    PromoImage {
        ...ContentUrl
        ...ContentReferenceItem
    }
    Heading
    SubHeading
    Author
    Body {
        html
    }
    ReadTime
    InfographicImage {
        ...ContentUrl
        ...ContentReferenceItem
    }
    VideoYoutube
    VideoTranscriptLink {
        default
    }
    ArticleTaxonomy {
        ArticleTopic
        SubtopicAuto
        SubtopicFinancialHardship
        SubtopicHome
        SubtopicLifeStages
        SubtopicPersonalFinances
        SubtopicRetirement
    }
    SeoSettings {
        ...PageSeoSettingsProperty
    }
    PageAdminSettings {
        ...PageAdminSettingsProperty
    }
}
