export interface ListOption {
    label: string;
    value: string;
}

export interface ListMeta {
    placeholder: string;
    autocomplete?: string;
}

export const LIST_META: Record<string, ListMeta> = {
    us_states:    { placeholder: 'Select a state...',              autocomplete: 'address-level1' },
    ca_provinces: { placeholder: 'Select a province...',           autocomplete: 'address-level1' },
    au_states:    { placeholder: 'Select a state or territory...', autocomplete: 'address-level1' },
    countries:    { placeholder: 'Select a country...',            autocomplete: 'country-name' },
    salutation:   { placeholder: 'Select a salutation...',         autocomplete: 'honorific-prefix' },
    industry:     { placeholder: 'Select an industry...' },
    job_level:    { placeholder: 'Select a job level...' },
};

export const PREBUILT_LISTS: Record<string, ListOption[]> = {

    us_states: [
        { label: 'Alabama',              value: 'AL' },
        { label: 'Alaska',               value: 'AK' },
        { label: 'Arizona',              value: 'AZ' },
        { label: 'Arkansas',             value: 'AR' },
        { label: 'California',           value: 'CA' },
        { label: 'Colorado',             value: 'CO' },
        { label: 'Connecticut',          value: 'CT' },
        { label: 'Delaware',             value: 'DE' },
        { label: 'District of Columbia', value: 'DC' },
        { label: 'Florida',              value: 'FL' },
        { label: 'Georgia',              value: 'GA' },
        { label: 'Hawaii',               value: 'HI' },
        { label: 'Idaho',                value: 'ID' },
        { label: 'Illinois',             value: 'IL' },
        { label: 'Indiana',              value: 'IN' },
        { label: 'Iowa',                 value: 'IA' },
        { label: 'Kansas',               value: 'KS' },
        { label: 'Kentucky',             value: 'KY' },
        { label: 'Louisiana',            value: 'LA' },
        { label: 'Maine',                value: 'ME' },
        { label: 'Maryland',             value: 'MD' },
        { label: 'Massachusetts',        value: 'MA' },
        { label: 'Michigan',             value: 'MI' },
        { label: 'Minnesota',            value: 'MN' },
        { label: 'Mississippi',          value: 'MS' },
        { label: 'Missouri',             value: 'MO' },
        { label: 'Montana',              value: 'MT' },
        { label: 'Nebraska',             value: 'NE' },
        { label: 'Nevada',               value: 'NV' },
        { label: 'New Hampshire',        value: 'NH' },
        { label: 'New Jersey',           value: 'NJ' },
        { label: 'New Mexico',           value: 'NM' },
        { label: 'New York',             value: 'NY' },
        { label: 'North Carolina',       value: 'NC' },
        { label: 'North Dakota',         value: 'ND' },
        { label: 'Ohio',                 value: 'OH' },
        { label: 'Oklahoma',             value: 'OK' },
        { label: 'Oregon',               value: 'OR' },
        { label: 'Pennsylvania',         value: 'PA' },
        { label: 'Rhode Island',         value: 'RI' },
        { label: 'South Carolina',       value: 'SC' },
        { label: 'South Dakota',         value: 'SD' },
        { label: 'Tennessee',            value: 'TN' },
        { label: 'Texas',                value: 'TX' },
        { label: 'Utah',                 value: 'UT' },
        { label: 'Vermont',              value: 'VT' },
        { label: 'Virginia',             value: 'VA' },
        { label: 'Washington',           value: 'WA' },
        { label: 'West Virginia',        value: 'WV' },
        { label: 'Wisconsin',            value: 'WI' },
        { label: 'Wyoming',              value: 'WY' },
    ],

    ca_provinces: [
        { label: 'Alberta',                    value: 'AB' },
        { label: 'British Columbia',           value: 'BC' },
        { label: 'Manitoba',                   value: 'MB' },
        { label: 'New Brunswick',              value: 'NB' },
        { label: 'Newfoundland and Labrador',  value: 'NL' },
        { label: 'Northwest Territories',      value: 'NT' },
        { label: 'Nova Scotia',                value: 'NS' },
        { label: 'Nunavut',                    value: 'NU' },
        { label: 'Ontario',                    value: 'ON' },
        { label: 'Prince Edward Island',       value: 'PE' },
        { label: 'Quebec',                     value: 'QC' },
        { label: 'Saskatchewan',               value: 'SK' },
        { label: 'Yukon',                      value: 'YT' },
    ],

    au_states: [
        { label: 'Australian Capital Territory', value: 'ACT' },
        { label: 'New South Wales',              value: 'NSW' },
        { label: 'Northern Territory',           value: 'NT' },
        { label: 'Queensland',                   value: 'QLD' },
        { label: 'South Australia',              value: 'SA' },
        { label: 'Tasmania',                     value: 'TAS' },
        { label: 'Victoria',                     value: 'VIC' },
        { label: 'Western Australia',            value: 'WA' },
    ],

    salutation: [
        { label: 'Mr.',   value: 'Mr.' },
        { label: 'Mrs.',  value: 'Mrs.' },
        { label: 'Ms.',   value: 'Ms.' },
        { label: 'Miss',  value: 'Miss' },
        { label: 'Dr.',   value: 'Dr.' },
        { label: 'Prof.', value: 'Prof.' },
    ],

    industry: [
        { label: 'Technology',                    value: 'technology' },
        { label: 'Healthcare',                    value: 'healthcare' },
        { label: 'Financial Services',            value: 'financial_services' },
        { label: 'Retail & E-commerce',           value: 'retail_ecommerce' },
        { label: 'Manufacturing',                 value: 'manufacturing' },
        { label: 'Education',                     value: 'education' },
        { label: 'Professional Services',         value: 'professional_services' },
        { label: 'Media & Entertainment',         value: 'media_entertainment' },
        { label: 'Government & Public Sector',    value: 'government' },
        { label: 'Non-profit',                    value: 'nonprofit' },
        { label: 'Real Estate',                   value: 'real_estate' },
        { label: 'Transportation & Logistics',    value: 'transportation_logistics' },
        { label: 'Energy & Utilities',            value: 'energy_utilities' },
        { label: 'Other',                         value: 'other' },
    ],

    job_level: [
        { label: 'C-Suite / Executive',      value: 'c_suite' },
        { label: 'VP / Director',            value: 'vp_director' },
        { label: 'Manager',                  value: 'manager' },
        { label: 'Individual Contributor',   value: 'individual_contributor' },
        { label: 'Consultant / Freelancer',  value: 'consultant_freelancer' },
        { label: 'Student',                  value: 'student' },
        { label: 'Other',                    value: 'other' },
    ],

    countries: [
        { label: 'United States',                        value: 'US' },
        { label: 'Afghanistan',                          value: 'AF' },
        { label: 'Albania',                              value: 'AL' },
        { label: 'Algeria',                              value: 'DZ' },
        { label: 'Andorra',                              value: 'AD' },
        { label: 'Angola',                               value: 'AO' },
        { label: 'Argentina',                            value: 'AR' },
        { label: 'Armenia',                              value: 'AM' },
        { label: 'Australia',                            value: 'AU' },
        { label: 'Austria',                              value: 'AT' },
        { label: 'Azerbaijan',                           value: 'AZ' },
        { label: 'Bahamas',                              value: 'BS' },
        { label: 'Bahrain',                              value: 'BH' },
        { label: 'Bangladesh',                           value: 'BD' },
        { label: 'Belarus',                              value: 'BY' },
        { label: 'Belgium',                              value: 'BE' },
        { label: 'Belize',                               value: 'BZ' },
        { label: 'Benin',                                value: 'BJ' },
        { label: 'Bhutan',                               value: 'BT' },
        { label: 'Bolivia',                              value: 'BO' },
        { label: 'Bosnia and Herzegovina',               value: 'BA' },
        { label: 'Botswana',                             value: 'BW' },
        { label: 'Brazil',                               value: 'BR' },
        { label: 'Brunei',                               value: 'BN' },
        { label: 'Bulgaria',                             value: 'BG' },
        { label: 'Burkina Faso',                         value: 'BF' },
        { label: 'Burundi',                              value: 'BI' },
        { label: 'Cambodia',                             value: 'KH' },
        { label: 'Cameroon',                             value: 'CM' },
        { label: 'Canada',                               value: 'CA' },
        { label: 'Cape Verde',                           value: 'CV' },
        { label: 'Central African Republic',             value: 'CF' },
        { label: 'Chad',                                 value: 'TD' },
        { label: 'Chile',                                value: 'CL' },
        { label: 'China',                                value: 'CN' },
        { label: 'Colombia',                             value: 'CO' },
        { label: 'Comoros',                              value: 'KM' },
        { label: 'Congo',                                value: 'CG' },
        { label: 'Costa Rica',                           value: 'CR' },
        { label: 'Croatia',                              value: 'HR' },
        { label: 'Cuba',                                 value: 'CU' },
        { label: 'Cyprus',                               value: 'CY' },
        { label: 'Czech Republic',                       value: 'CZ' },
        { label: 'Denmark',                              value: 'DK' },
        { label: 'Djibouti',                             value: 'DJ' },
        { label: 'Dominican Republic',                   value: 'DO' },
        { label: 'DR Congo',                             value: 'CD' },
        { label: 'Ecuador',                              value: 'EC' },
        { label: 'Egypt',                                value: 'EG' },
        { label: 'El Salvador',                          value: 'SV' },
        { label: 'Equatorial Guinea',                    value: 'GQ' },
        { label: 'Eritrea',                              value: 'ER' },
        { label: 'Estonia',                              value: 'EE' },
        { label: 'Eswatini',                             value: 'SZ' },
        { label: 'Ethiopia',                             value: 'ET' },
        { label: 'Fiji',                                 value: 'FJ' },
        { label: 'Finland',                              value: 'FI' },
        { label: 'France',                               value: 'FR' },
        { label: 'Gabon',                                value: 'GA' },
        { label: 'Gambia',                               value: 'GM' },
        { label: 'Georgia',                              value: 'GE' },
        { label: 'Germany',                              value: 'DE' },
        { label: 'Ghana',                                value: 'GH' },
        { label: 'Greece',                               value: 'GR' },
        { label: 'Guatemala',                            value: 'GT' },
        { label: 'Guinea',                               value: 'GN' },
        { label: 'Guinea-Bissau',                        value: 'GW' },
        { label: 'Guyana',                               value: 'GY' },
        { label: 'Haiti',                                value: 'HT' },
        { label: 'Honduras',                             value: 'HN' },
        { label: 'Hungary',                              value: 'HU' },
        { label: 'Iceland',                              value: 'IS' },
        { label: 'India',                                value: 'IN' },
        { label: 'Indonesia',                            value: 'ID' },
        { label: 'Iran',                                 value: 'IR' },
        { label: 'Iraq',                                 value: 'IQ' },
        { label: 'Ireland',                              value: 'IE' },
        { label: 'Israel',                               value: 'IL' },
        { label: 'Italy',                                value: 'IT' },
        { label: 'Ivory Coast',                          value: 'CI' },
        { label: 'Jamaica',                              value: 'JM' },
        { label: 'Japan',                                value: 'JP' },
        { label: 'Jordan',                               value: 'JO' },
        { label: 'Kazakhstan',                           value: 'KZ' },
        { label: 'Kenya',                                value: 'KE' },
        { label: 'Kosovo',                               value: 'XK' },
        { label: 'Kuwait',                               value: 'KW' },
        { label: 'Kyrgyzstan',                           value: 'KG' },
        { label: 'Laos',                                 value: 'LA' },
        { label: 'Latvia',                               value: 'LV' },
        { label: 'Lebanon',                              value: 'LB' },
        { label: 'Lesotho',                              value: 'LS' },
        { label: 'Liberia',                              value: 'LR' },
        { label: 'Libya',                                value: 'LY' },
        { label: 'Liechtenstein',                        value: 'LI' },
        { label: 'Lithuania',                            value: 'LT' },
        { label: 'Luxembourg',                           value: 'LU' },
        { label: 'Madagascar',                           value: 'MG' },
        { label: 'Malawi',                               value: 'MW' },
        { label: 'Malaysia',                             value: 'MY' },
        { label: 'Maldives',                             value: 'MV' },
        { label: 'Mali',                                 value: 'ML' },
        { label: 'Malta',                                value: 'MT' },
        { label: 'Mauritania',                           value: 'MR' },
        { label: 'Mauritius',                            value: 'MU' },
        { label: 'Mexico',                               value: 'MX' },
        { label: 'Moldova',                              value: 'MD' },
        { label: 'Monaco',                               value: 'MC' },
        { label: 'Mongolia',                             value: 'MN' },
        { label: 'Montenegro',                           value: 'ME' },
        { label: 'Morocco',                              value: 'MA' },
        { label: 'Mozambique',                           value: 'MZ' },
        { label: 'Myanmar',                              value: 'MM' },
        { label: 'Namibia',                              value: 'NA' },
        { label: 'Nepal',                                value: 'NP' },
        { label: 'Netherlands',                          value: 'NL' },
        { label: 'New Zealand',                          value: 'NZ' },
        { label: 'Nicaragua',                            value: 'NI' },
        { label: 'Niger',                                value: 'NE' },
        { label: 'Nigeria',                              value: 'NG' },
        { label: 'North Korea',                          value: 'KP' },
        { label: 'North Macedonia',                      value: 'MK' },
        { label: 'Norway',                               value: 'NO' },
        { label: 'Oman',                                 value: 'OM' },
        { label: 'Pakistan',                             value: 'PK' },
        { label: 'Palestine',                            value: 'PS' },
        { label: 'Panama',                               value: 'PA' },
        { label: 'Papua New Guinea',                     value: 'PG' },
        { label: 'Paraguay',                             value: 'PY' },
        { label: 'Peru',                                 value: 'PE' },
        { label: 'Philippines',                          value: 'PH' },
        { label: 'Poland',                               value: 'PL' },
        { label: 'Portugal',                             value: 'PT' },
        { label: 'Qatar',                                value: 'QA' },
        { label: 'Romania',                              value: 'RO' },
        { label: 'Russia',                               value: 'RU' },
        { label: 'Rwanda',                               value: 'RW' },
        { label: 'San Marino',                           value: 'SM' },
        { label: 'Saudi Arabia',                         value: 'SA' },
        { label: 'Senegal',                              value: 'SN' },
        { label: 'Serbia',                               value: 'RS' },
        { label: 'Sierra Leone',                         value: 'SL' },
        { label: 'Singapore',                            value: 'SG' },
        { label: 'Slovakia',                             value: 'SK' },
        { label: 'Slovenia',                             value: 'SI' },
        { label: 'Somalia',                              value: 'SO' },
        { label: 'South Africa',                         value: 'ZA' },
        { label: 'South Korea',                          value: 'KR' },
        { label: 'South Sudan',                          value: 'SS' },
        { label: 'Spain',                                value: 'ES' },
        { label: 'Sri Lanka',                            value: 'LK' },
        { label: 'Sudan',                                value: 'SD' },
        { label: 'Sweden',                               value: 'SE' },
        { label: 'Switzerland',                          value: 'CH' },
        { label: 'Syria',                                value: 'SY' },
        { label: 'Taiwan',                               value: 'TW' },
        { label: 'Tajikistan',                           value: 'TJ' },
        { label: 'Tanzania',                             value: 'TZ' },
        { label: 'Thailand',                             value: 'TH' },
        { label: 'Timor-Leste',                          value: 'TL' },
        { label: 'Togo',                                 value: 'TG' },
        { label: 'Trinidad and Tobago',                  value: 'TT' },
        { label: 'Tunisia',                              value: 'TN' },
        { label: 'Turkey',                               value: 'TR' },
        { label: 'Turkmenistan',                         value: 'TM' },
        { label: 'Uganda',                               value: 'UG' },
        { label: 'Ukraine',                              value: 'UA' },
        { label: 'United Arab Emirates',                 value: 'AE' },
        { label: 'United Kingdom',                       value: 'GB' },
        { label: 'Uruguay',                              value: 'UY' },
        { label: 'Uzbekistan',                           value: 'UZ' },
        { label: 'Venezuela',                            value: 'VE' },
        { label: 'Vietnam',                              value: 'VN' },
        { label: 'Yemen',                                value: 'YE' },
        { label: 'Zambia',                               value: 'ZM' },
        { label: 'Zimbabwe',                             value: 'ZW' },
    ],
};
