fragment IngredientDisclosurePage on IngredientDisclosurePage {
    _metadata {
        ...PageUrl
        published
        displayName
    }
    ProductName
    ProductCategory
    MaterialNumbers
    IntentionallyAddedIngredients {
        key
        item {
            __typename
            _metadata { key displayName types }
            ... on IngredientEntry {
                IngredientName
                CasNumber
                Function
                OnDesignatedList { html }
            }
        }
    }
    FragranceComponents {
        key
        item {
            __typename
            _metadata { key displayName types }
            ... on IngredientEntry {
                IngredientName
                CasNumber
                Function
                OnDesignatedList { html }
            }
        }
    }
    SdsLink {
        ...LinkUrl
    }
    DisclosureDate
    SeoSettings {
        ...PageSeoSettingsProperty
    }
}
