query redirectById($key: [String], $loc: [Locales], $ver: String) {
    _Page(
        ids: $key
        locale: $loc
        where: { _metadata: { version: { eq: $ver } } }
        variation: { include: ALL }
    ) {
        item {
            ... on ArticlePage {
                PageAdminSettings {
                    RedirectUrl {
                        url {
                            default
                        }
                    }
                }
            }
            ... on BlankExperience {
                PageAdminSettings {
                    RedirectUrl {
                        url {
                            default
                        }
                    }
                }
            }
        }
    }
}
